version: '2'
services:  
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bike
      - SPRING_DATASOURCE_USERNAME=bike
      - SPRING_DATASOURCE_PASSWORD=b1k3P4ss!.
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8080"      
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=bike
      - POSTGRES_PASSWORD=b1k3P4ss!.
    ports:
      - "5432:5432"      
